import io
import logging
import smtplib
import uuid
from datetime import datetime
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)


REPORT_TEMPLATE = """
Dear Maryland SHA Customer Service,

This is an automated pothole incident report generated by the AI Eyes on the Road system.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
INCIDENT REPORT — POTHOLE DETECTION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Reference Number   : {ref_number}
Report Type        : {report_type}
Report Date        : {report_date}

LOCATION DETAILS
─────────────────
GPS Coordinates    : {latitude}, {longitude}
Google Maps Link   : https://maps.google.com/?q={latitude},{longitude}

DETECTION DETAILS
─────────────────
First Detected     : {first_seen}
Last Detected      : {last_seen}
Total Detections   : {detection_count}
Confidence Score   : {confidence:.1%}
Risk Level         : {risk_level}
Estimated Distance : {distance} metres

EVIDENCE
────────
A frame snapshot has been attached to this email for visual reference.

{additional_notes}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
This report was generated automatically. Please acknowledge receipt
and provide an estimated repair timeline.

Submitted by the AI Eyes on the Road System
Powered by YOLOv8 + OpenCV Computer Vision
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

FOLLOWUP_TEMPLATE = """
Dear Maryland SHA Customer Service,

This is a FOLLOW-UP to our previous pothole report (Reference: {ref_number}).

As of {followup_date}, no acknowledgment has been received for the pothole
reported on {original_date} at coordinates {latitude}, {longitude}.

We respectfully request an update on the repair status.

{additional_notes}

If this issue has already been resolved, please disregard this message
and notify us at {reply_email} to update our records.

Reference: {ref_number}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
AI Eyes on the Road — Automated Reporting
"""

ESCALATION_TEMPLATE = """
FORMAL ESCALATION NOTICE

Re: Unresolved Pothole Hazard — Ref: {ref_number}

Maryland Department of Transportation
State Highway Administration

To Whom It May Concern:

This constitutes a formal escalation notice regarding a road hazard
that was reported on {original_date} and remains unaddressed as of {escalation_date}.

HAZARD DETAILS
Location   : {latitude}, {longitude}
Severity   : {risk_level}
Days Open  : {days_open}

This pothole presents a public safety hazard. We request immediate
attention and a written response within 5 business days.

Failure to respond may result in this report being shared with:
- Maryland Governor's Office
- Local County Government
- Public Safety Authorities

{additional_notes}

Reference: {ref_number}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
AI Eyes on the Road — Automated Reporting System
"""


class MDOTReporter:
    """
    Handles automated report generation and email submission.
    """

    def __init__(self, config, db_ops=None, static_dir: str = "static"):
        self.config = config
        self.db = db_ops
        self.static_dir = Path(static_dir)

    #Public API────────

    def submit_initial_report(self, pothole: dict) -> dict:
        """
        Generate and send an initial pothole report to MDOT.

        Args:
            pothole: dict from Pothole.to_dict()

        Returns:
            dict with status, reference_number, error
        """
        ref = self._gen_ref()
        body = REPORT_TEMPLATE.format(
            ref_number=ref,
            report_type="Initial Report",
            report_date=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
            latitude=pothole.get("latitude") or "Unknown",
            longitude=pothole.get("longitude") or "Unknown",
            first_seen=pothole.get("first_seen") or "Unknown",
            last_seen=pothole.get("last_seen") or "Unknown",
            detection_count=pothole.get("detection_count", 1),
            confidence=pothole.get("confidence", 0.0),
            risk_level=pothole.get("risk_level", "unknown").upper(),
            distance=pothole.get("estimated_distance_m") or "Unknown",
            additional_notes="",
        )

        subject = f"[Pothole Report #{ref}] Road Hazard at {pothole.get('latitude')}, {pothole.get('longitude')}"
        attachment = self._get_snapshot(pothole.get("snapshot_path"))

        status, error = self._send_email(
            subject=subject, body=body, attachment=attachment
        )

        #Persist to DB
        if self.db:
            try:
                self.db.create_report(
                    pothole_id=pothole["id"],
                    recipient_email=self.config.MDOT_REPORT_EMAIL,
                    subject=subject,
                    report_type="initial",
                    status=status,
                    reference_number=ref,
                    error_message=error,
                )
            except Exception as exc:
                logger.warning("DB report save failed: %s", exc)

        return {"status": status, "reference_number": ref, "error": error}

    def submit_followup(self, pothole: dict, report: dict) -> dict:
        ref = report.get("reference_number", self._gen_ref())
        body = FOLLOWUP_TEMPLATE.format(
            ref_number=ref,
            followup_date=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
            original_date=report.get("submitted_at", "Unknown"),
            latitude=pothole.get("latitude") or "Unknown",
            longitude=pothole.get("longitude") or "Unknown",
            additional_notes="",
            reply_email=self.config.REPORT_FROM_EMAIL or "N/A",
        )

        subject = f"[FOLLOW-UP #{ref}] Pothole Report — Awaiting Response"
        status, error = self._send_email(subject=subject, body=body)

        if self.db:
            try:
                self.db.create_report(
                    pothole_id=pothole["id"],
                    recipient_email=self.config.MDOT_REPORT_EMAIL,
                    subject=subject,
                    report_type="followup",
                    status=status,
                    reference_number=ref,
                    error_message=error,
                )
            except Exception as exc:
                logger.warning("DB followup save failed: %s", exc)

        return {"status": status, "reference_number": ref, "error": error}

    def submit_escalation(self, pothole: dict, report: dict, days_open: int) -> dict:
        ref = report.get("reference_number", self._gen_ref())
        body = ESCALATION_TEMPLATE.format(
            ref_number=ref,
            original_date=report.get("submitted_at", "Unknown"),
            escalation_date=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
            latitude=pothole.get("latitude") or "Unknown",
            longitude=pothole.get("longitude") or "Unknown",
            risk_level=pothole.get("risk_level", "unknown").upper(),
            days_open=days_open,
            additional_notes="",
        )

        subject = f"[ESCALATION #{ref}] URGENT: Unresolved Pothole Hazard"
        status, error = self._send_email(subject=subject, body=body)

        if self.db:
            try:
                self.db.create_report(
                    pothole_id=pothole["id"],
                    recipient_email=self.config.MDOT_REPORT_EMAIL,
                    subject=subject,
                    report_type="escalation",
                    status=status,
                    reference_number=ref,
                    error_message=error,
                )
            except Exception as exc:
                logger.warning("DB escalation save failed: %s", exc)

        return {"status": status, "reference_number": ref, "error": error}

    def generate_report_text(self, pothole: dict) -> str:
        """Return formatted report text without sending (for preview)."""
        ref = self._gen_ref()
        return REPORT_TEMPLATE.format(
            ref_number=ref,
            report_type="Preview",
            report_date=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
            latitude=pothole.get("latitude") or "Not available",
            longitude=pothole.get("longitude") or "Not available",
            first_seen=pothole.get("first_seen") or "Unknown",
            last_seen=pothole.get("last_seen") or "Unknown",
            detection_count=pothole.get("detection_count", 1),
            confidence=pothole.get("confidence", 0.0),
            risk_level=pothole.get("risk_level", "unknown").upper(),
            distance=pothole.get("estimated_distance_m") or "Unknown",
            additional_notes="[This is a preview — not sent]",
        )

    #Private

    def send_personal_alert(self, pothole: dict, to_email: str) -> dict:
        """
        Send a personal alert email with snapshot attachment.
        Uses the same SMTP credentials as MDOT reporting but to a custom recipient.
        """
        pid   = pothole.get("id", "?")
        lat   = pothole.get("latitude")  or "N/A"
        lng   = pothole.get("longitude") or "N/A"
        risk  = (pothole.get("risk_level") or "unknown").upper()
        conf  = f"{pothole.get('confidence', 0) * 100:.0f}%"
        seen  = pothole.get("last_seen") or pothole.get("first_seen") or "Unknown"
        dist  = pothole.get("estimated_distance_m") or "N/A"
        ref   = self._gen_ref()
        maps_link = f"https://www.openstreetmap.org/?mlat={lat}&mlon={lng}&zoom=17"

        body = (
            f"Dear Sir/Madam,\n\n"
            f"A pothole has been detected and confirmed by the AI Eyes on the Road system.\n\n"
            f"INCIDENT DETAILS\n"
            f"{'─' * 36}\n"
            f"Pothole ID      : #{pid}\n"
            f"Risk Level      : {risk}\n"
            f"Confidence      : {conf}\n"
            f"Distance        : {dist} m\n"
            f"GPS Coordinates : {lat}, {lng}\n"
            f"Detected At     : {seen}\n"
            f"Map Link        : {maps_link}\n"
            f"Reference       : {ref}\n\n"
            f"A snapshot is attached for visual reference.\n"
            f"Please arrange for prompt inspection and repair.\n\n"
            f"Regards,\n"
            f"AI Eyes on the Road — Automated Reporting System\n"
        )

        subject    = f"Pothole Hazard Report — ID #{pid} [{risk}] (Ref: {ref})"
        attachment = self._get_snapshot(pothole.get("snapshot_path"))
        fname      = f"pothole_{pid}_snapshot.jpg"

        status, error = self._send_email(
            subject=subject, body=body,
            attachment=attachment, attachment_name=fname,
            to_email=to_email,
        )
        return {"status": status, "reference_number": ref, "error": error}

    def _send_email(
        self,
        subject: str,
        body: str,
        attachment: Optional[bytes] = None,
        attachment_name: str = "snapshot.jpg",
        to_email: Optional[str] = None,
    ) -> tuple[str, Optional[str]]:
        """
        Send email via SMTP. Returns (status, error_message).
        status: 'sent' | 'failed' | 'dry_run'
        """
        from_email = self.config.REPORT_FROM_EMAIL
        to_email   = to_email or self.config.MDOT_REPORT_EMAIL

        if not from_email or not self.config.SMTP_USERNAME:
            logger.info("Email not configured — dry run report logged.")
            logger.info("SUBJECT: %s", subject)
            logger.info("BODY:\n%s", body[:400])
            return "dry_run", None

        try:
            msg = MIMEMultipart()
            msg["From"] = from_email
            msg["To"] = to_email
            msg["Subject"] = subject
            msg.attach(MIMEText(body, "plain"))

            if attachment:
                part = MIMEBase("application", "octet-stream")
                part.set_payload(attachment)
                encoders.encode_base64(part)
                part.add_header(
                    "Content-Disposition", f'attachment; filename="{attachment_name}"'
                )
                msg.attach(part)

            with smtplib.SMTP(self.config.SMTP_SERVER, self.config.SMTP_PORT) as server:
                server.ehlo()
                server.starttls()
                server.login(self.config.SMTP_USERNAME, self.config.SMTP_PASSWORD)
                server.sendmail(from_email, to_email, msg.as_string())

            logger.info("Email sent: %s → %s", subject[:60], to_email)
            return "sent", None

        except Exception as exc:
            logger.error("Email send failed: %s", exc)
            return "failed", str(exc)

    def _get_snapshot(self, rel_path: Optional[str]) -> Optional[bytes]:
        if not rel_path:
            return None
        full = self.static_dir / rel_path
        if full.exists():
            return full.read_bytes()
        return None

    @staticmethod
    def _gen_ref() -> str:
        return f"SHA-{datetime.utcnow().strftime('%Y%m%d')}-{uuid.uuid4().hex[:6].upper()}"
