
import json
import sys
from pathlib import Path

import torch
import yaml

PROJECT_ROOT = Path("/workspace/Pothole-I")
DATASET_DIR  = PROJECT_ROOT / "Pothole-Detection-1"
FIXED_YAML   = DATASET_DIR / "data_abs.yaml"     #generated by train_gpu.py
ORIG_YAML    = DATASET_DIR / "data.yaml"
DEFAULT_WEIGHTS = PROJECT_ROOT / "models" / "best.pt"


def _get_yaml() -> Path:
    """Prefer the absolute-path yaml generated at training time."""
    if FIXED_YAML.exists():
        return FIXED_YAML
    #Fallback: generate it now if train_gpu.py hasn't been run yet
    print("[eval] data_abs.yaml not found — generating from data.yaml ...")
    cfg = yaml.safe_load(open(ORIG_YAML))
    cfg["train"] = str(DATASET_DIR / "train" / "images")
    cfg["val"]   = str(DATASET_DIR / "valid" / "images")
    cfg["test"]  = str(DATASET_DIR / "test"  / "images")
    if cfg.get("names") in (["0"], [0]):
        cfg["names"] = ["pothole"]
    with open(FIXED_YAML, "w") as f:
        yaml.dump(cfg, f, default_flow_style=False, sort_keys=False)
    return FIXED_YAML


def evaluate(
    weights: Path,
    split: str = "test",
    imgsz: int = 640,
    batch: int = 32,
    device: str = "cuda:0",
    conf: float = 0.001,     #keep low — gives full PR curve
    iou: float = 0.60,
) -> dict:
    from ultralytics import YOLO

    if not weights.exists():
        print(f"[ERROR] Weights not found: {weights}")
        sys.exit(1)

    data_yaml = _get_yaml()
    save_dir = weights.parent.parent / "eval"

    #Clear VRAM before evaluation
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        free_gb = torch.cuda.mem_get_info(0)[0] / 1e9
        print(f"[eval] VRAM free before eval: {free_gb:.1f} GB")

    print(f"\n[eval] Weights  : {weights}")
    print(f"[eval] Dataset  : {data_yaml}")
    print(f"[eval] Split    : {split}")
    print(f"[eval] Device   : {device}")
    print(f"[eval] Batch    : {batch}")

    model = YOLO(str(weights))

    results = model.val(
        data=str(data_yaml),
        split=split,
        imgsz=imgsz,
        batch=batch,
        device=device,
        conf=conf,
        iou=iou,
        project=str(save_dir.parent),
        name=save_dir.name,
        plots=True,
        save_json=True,
        verbose=True,
        exist_ok=True,
    )

    box = results.box

    #Per-class metrics
    cfg = yaml.safe_load(open(data_yaml))
    class_names = cfg.get("names", [])
    per_class = {}
    if hasattr(box, "ap_class_index") and box.ap_class_index is not None:
        for i, cls_idx in enumerate(box.ap_class_index):
            name = class_names[cls_idx] if cls_idx < len(class_names) else f"cls_{cls_idx}"
            per_class[name] = {
                "mAP50":     round(float(box.ap50[i]),  4) if hasattr(box, "ap50") else None,
                "precision": round(float(box.p[i]),     4) if hasattr(box, "p")    else None,
                "recall":    round(float(box.r[i]),     4) if hasattr(box, "r")    else None,
            }

    summary = {
        "weights":   str(weights),
        "dataset":   str(data_yaml),
        "split":     split,
        "mAP50":     round(float(box.map50), 4),
        "mAP50_95":  round(float(box.map),   4),
        "precision": round(float(box.mp),    4),
        "recall":    round(float(box.mr),    4),
        "per_class": per_class,
        "results_dir": str(save_dir),
    }

    #Save JSON
    save_dir.mkdir(parents=True, exist_ok=True)
    json_path = save_dir / "eval_summary.json"
    with open(json_path, "w") as f:
        json.dump(summary, f, indent=2)

    _print_report(summary)
    print(f"\n[eval] Plots saved → {save_dir}")
    print(f"[eval] JSON        → {json_path}")

    #Free VRAM
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    return summary


def _print_report(s: dict):
    w = 52
    mAP50    = s["mAP50"]
    mAP5095  = s["mAP50_95"]
    prec     = s["precision"]
    rec      = s["recall"]
    f1       = 2 * prec * rec / (prec + rec + 1e-9)

    print("\n" + "=" * w)
    print("  EVALUATION RESULTS")
    print("=" * w)
    print(f"  mAP50       : {mAP50:.4f}   ({mAP50*100:.1f}%)")
    print(f"  mAP50-95    : {mAP5095:.4f}   ({mAP5095*100:.1f}%)")
    print(f"  Precision   : {prec:.4f}")
    print(f"  Recall      : {rec:.4f}")
    print(f"  F1 score    : {f1:.4f}")

    if s["per_class"]:
        print(f"\n  Per-class:")
        print(f"  {'Class':<20} {'mAP50':>7} {'Prec':>7} {'Rec':>7}")
        print("  " + "-" * 44)
        for cls, m in s["per_class"].items():
            mAP  = f"{m['mAP50']:.4f}"     if m.get("mAP50")    is not None else "  N/A "
            p    = f"{m['precision']:.4f}" if m.get("precision") is not None else "  N/A "
            r    = f"{m['recall']:.4f}"    if m.get("recall")    is not None else "  N/A "
            print(f"  {cls:<20} {mAP:>7} {p:>7} {r:>7}")

    print("=" * w)

    #Guidance
    print("\n  Diagnostics:")
    if mAP50 >= 0.85:
        print(f"  [✓] mAP50={mAP50:.2f} — exceeds target (>0.85). Model is production-ready.")
        print("      Consider exporting: python training/export.py --weights <path>")
    elif mAP50 >= 0.70:
        print(f"  [~] mAP50={mAP50:.2f} — good. Try:")
        print("      - Continue training: --epochs 150 --resume")
        print("      - Larger model: --model yolov8s.pt")
    elif mAP50 >= 0.50:
        print(f"  [!] mAP50={mAP50:.2f} — moderate. Actions:")
        print("      - More data (augmentation or additional Roboflow datasets)")
        print("      - Lower confidence threshold: POTHOLE_CONFIDENCE=0.20 in config.py")
        print("      - Larger model: yolov8s.pt or yolov8m.pt")
    else:
        print(f"  [✗] mAP50={mAP50:.2f} — underfit. Check:")
        print("      - data.yaml paths: python scripts/verify_gpu.py")
        print("      - Training didn't converge: check runs/train/exp/results.png")
        print("      - Dataset quality: are labels correct?")

    if prec < 0.60:
        print(f"\n  [!] Precision={prec:.2f} — false positives are high.")
        print("      Raise POTHOLE_CONFIDENCE in config.py (try 0.40–0.50).")
    if rec < 0.60:
        print(f"\n  [!] Recall={rec:.2f} — missing too many potholes.")
        print("      Lower POTHOLE_CONFIDENCE in config.py (try 0.20–0.25).")


#CLI──

import argparse

def main():
    parser = argparse.ArgumentParser(
        description="Evaluate trained pothole model",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--weights", default=str(DEFAULT_WEIGHTS),
                        help="Path to best.pt")
    parser.add_argument("--split", default="test", choices=["val", "test"])
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--batch", type=int, default=32)
    parser.add_argument("--device", default="cuda:0")
    parser.add_argument("--conf", type=float, default=0.001)
    parser.add_argument("--iou", type=float, default=0.60)
    args = parser.parse_args()

    evaluate(
        weights=Path(args.weights),
        split=args.split,
        imgsz=args.imgsz,
        batch=args.batch,
        device=args.device,
        conf=args.conf,
        iou=args.iou,
    )


if __name__ == "__main__":
    main()
